### ISSUE TITLE
Implement transport standard RFC 6587

### ISSUE THREAD

**Issue by vbohata** [logstash-plugins/logstash-input-syslog#65]
There is RFC 6587 - transmission of Syslog Messages over TCP. We have some sources which follow this standard and we are unable to ingest them as syslog message splitting is not per new line but controlled by octet counting - https://tools.ietf.org/html/rfc6587#section-3.4

I think this plugin should support it.

**Comment by drolfe** [comment]
This is causing a massive issue for us 

We are receiving juniper srx traffic logs over tcp and need to use logstash the filter the messages 

any ETA on logstash support for this RFC framing ?

**Comment by drolfe** [comment]
I'm unfamiliar with filebeat configuration

What I'm thinking is to use filebeat as a shim layer for the RFC6587 framing ie

- RFC6587 syslog => 
- Filebeat(to split out the syslog messages from the framing) => 
- Logstash(to filter the messages) => 
- Elastic or further processing 

Would something like the below work to get the syslog to be understood by logstash ? 

```
filebeat.inputs:
- type: syslog
  format: rfc5424
  framing: rfc6587
  protocol.tcp:
    host: "0.0.0.0:514"

output.logstash:
  hosts: ["10.10.10.5:5044"]

```
